### ISSUE TITLE
Custom type is not loaded

### ISSUE THREAD

**Issue by vbelorus** [overblog/GraphQLBundle#278]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | master

Hi there
After last update master branch I have an issue.
I have custom type in php that extends ScalarType, but it's not loaded ( throw \Overblog\GraphQLBundle\Resolver\UnresolvableException). 

I found that TypeResolver cannot get solution in 
https://github.com/overblog/GraphQLBundle/blob/5d25197211dda883b7909ff0a039303519aabb70/Resolver/TypeResolver.php#L52

BUT! If we call $this->getSolutions(); before $this->getSolution($alias) - it works.
In \Overblog\GraphQLBundle\Resolver\AbstractResolver::getSolutions we load solutions and somehow sometimes it's not loading before getting solution by alias.

```
#0 /app/vendor/overblog/graphql-bundle/Resolver/TypeResolver.php(46): Overblog\GraphQLBundle\Resolver\TypeResolver->baseType('UUID')
#1 /app/vendor/overblog/graphql-bundle/Resolver/TypeResolver.php(32): Overblog\GraphQLBundle\Resolver\TypeResolver->string2Type('UUID')
#2 /app/var/cache/dev/overblog/graphql-bundle/__definitions__/QueryType.php(71): Overblog\GraphQLBundle\Resolver\TypeResolver->resolve('UUID')
#3 /app/vendor/overblog/graphql-bundle/Definition/ConfigProcessor/PublicFieldsFilterConfigProcessor.php(34): Overblog\GraphQLBundle\__DEFINITIONS__\QueryType->Overblog\GraphQLBundle\__DEFINITIONS__\{closure}()
#4 /app/vendor/overblog/graphql-bundle/Definition/ConfigProcessor/AclConfigProcessor.php(54): Overblog\GraphQLBundle\Definition\ConfigProcessor\PublicFieldsFilterConfigProcessor->Overblog\GraphQLBundle\Definition\ConfigProcessor\{closure}()
#5 /app/vendor/webonyx/graphql-php/src/Type/Definition/FieldDefinition.php(97): Overblog\GraphQLBundle\Definition\ConfigProcessor\AclConfigProcessor->Overblog\GraphQLBundle\Definition\ConfigProcessor\{closure}()
#6 /app/vendor/webonyx/graphql-php/src/Type/Definition/ObjectType.php(127): GraphQL\Type\Definition\FieldDefinition::defineFieldMap(Object(Overblog\GraphQLBundle\__DEFINITIONS__\QueryType), Object(Closure))
#7 /app/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php(125): GraphQL\Type\Definition\ObjectType->getFields()
#8 /app/vendor/webonyx/graphql-php/src/Type/Schema.php(223): GraphQL\Utils\TypeInfo::extractTypes(Object(Overblog\GraphQLBundle\__DEFINITIONS__\QueryType), Array)
#9 /app/vendor/webonyx/graphql-php/src/Type/Schema.php(195): GraphQL\Type\Schema->collectAllTypes()
#10 /app/vendor/webonyx/graphql-php/src/Type/Schema.php(418): GraphQL\Type\Schema->getTypeMap()
#11 /app/vendor/overblog/graphql-bundle/Definition/Builder/SchemaBuilder.php(49): GraphQL\Type\Schema->assertValid()
#12 /app/var/cache/dev/ContainerF0HmBmU/getOverblogGraphql_RequestExecutorService.php(12): Overblog\GraphQLBundle\Definition\Builder\SchemaBuilder->create('Query', 'Mutation', NULL, Array)
#13 /app/var/cache/dev/ContainerF0HmBmU/srcDevDebugProjectContainer.php(275): require('/app/var/cache/...')
#14 /app/var/cache/dev/ContainerF0HmBmU/getOverblogGraphql_Controller_GraphqlService.php(8): ContainerF0HmBmU\srcDevDebugProjectContainer->load('/app/var/cache/...')
#15 /app/var/cache/dev/ContainerF0HmBmU/srcDevDebugProjectContainer.php(275): require('/app/var/cache/...')
#16 /app/vendor/symfony/dependency-injection/Container.php(232): ContainerF0HmBmU\srcDevDebugProjectContainer->load('/app/var/cache/...')
#17 /app/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php(78): Symfony\Component\DependencyInjection\Container->get('overblog_graphq...')
#18 /app/vendor/symfony/framework-bundle/Controller/ControllerResolver.php(43): Symfony\Component\HttpKernel\Controller\ContainerControllerResolver->createController('overblog_graphq...')
#19 /app/vendor/symfony/http-kernel/Controller/ControllerResolver.php(69): Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver->createController('overblog_graphq...')
#20 /app/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php(41): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request))
#21 /app/vendor/symfony/http-kernel/Controller/TraceableControllerResolver.php(38): Symfony\Component\HttpKernel\Controller\ContainerControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request))
#22 /app/vendor/symfony/http-kernel/HttpKernel.php(132): Symfony\Component\HttpKernel\Controller\TraceableControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request))
#23 /app/vendor/symfony/http-kernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#24 /app/vendor/symfony/http-kernel/Kernel.php(190): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#25 /app/public/index.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#26 {main}
```

**Comment by mcg-web** [comment]
Hi @vbelorus can you try a `bin/console c:w` please?

**Comment by vbelorus** [comment]
@mcg-web 
Cache was warmed but I'm still have an exception.

**Comment by mcg-web** [comment]
what the output of this command `bin/console graphql:debug --category=type`?

**Comment by vbelorus** [comment]
```
GraphQL Types Services
======================

2018-01-20T19:42:14+00:00 [error] Error thrown while running command "graphql:debug --category=type". Message: "Notice: Undefined index: id"

In DebugCommand.php line 100:
                               
  Notice: Undefined index: id  
                               

graphql:debug [--category [CATEGORY]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

So, in my types $options is empty array. Because of this I have an error in DebugCommand.php line 100.

**Comment by mcg-web** [comment]
What solution do you use to define your scalar (service)?

**Comment by vbelorus** [comment]
Created type class:

```php
<?php

namespace App\GraphQL\Type;


use GraphQL\Error\Error;
use GraphQL\Language\AST\StringValueNode;
use GraphQL\Type\Definition\InputType;
use GraphQL\Type\Definition\ScalarType;
use GraphQL\Type\Definition\Type;
use Ramsey\Uuid\Uuid;

class UUIDType extends ScalarType
{
    /**
     * @var string
     */
    public $name = 'UUID';

    /**
     * @var string
     */
    public $description =
        'UUID type';

    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param $value Uuid
     * @return mixed
     */
    public function serialize($value)
    {
        return $value;
    }

    /**
     * @param $value
     * @return null|\Ramsey\Uuid\UuidInterface
     */
    public function parseValue($value)
    {
        return (Uuid::isValid($value)) ? Uuid::fromString($value) : null;
    }

    /**
     * @param \GraphQL\Language\AST\Node $ast
     * @return mixed|\Ramsey\Uuid\UuidInterface
     * @throws Error
     */
    public function parseLiteral($ast)
    {
        if (!($ast instanceof StringValueNode)) {
            throw new Error('Query error: Can only parse strings got: ' . $ast->kind, [$ast]);
        }
        if (!is_string($ast->value) || !Uuid::isValid($ast->value)) {
            throw new Error('Query error: Not a valid UUID', [$ast]);
        }
        return Uuid::fromString($ast->value);
    }
}
```

graphql.yaml config:
```
overblog_graphql:
    errors_handler:
        debug: true

    definitions:
        config_validation: "%kernel.debug%"
        auto_mapping:
            directories:
                - "%kernel.project_dir%/src/GraphQL/Type"
        schema:
            query: Query
            mutation: Mutation
        mappings:
            auto_discover: true
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~
    services:
        promise_adapter: "webonyx_graphql.sync_promise_adapter"
```

**Comment by mcg-web** [comment]
What is your type alias ? `$this->getSolution('UUID'); ` ?

**Comment by vbelorus** [comment]
@mcg-web 
yes, UUID

**Comment by mcg-web** [comment]
Try calling it with class name  `App\\GraphQL\\Type\\UUIDType`?

**Comment by mcg-web** [comment]
Here is [the solution to your issue](https://github.com/overblog/GraphQLBundle/blob/master/UPGRADE-0.11.md#type-automapping-and-symfony-di-autoconfigure), feel free to reopen if needed :+1: . Thanks again for your feedback!

**Comment by vbelorus** [comment]
@mcg-web 
It works! Thanks a lot
